CREATE TABLE public.food_portion (
	id int4 NULL,
	fdc_id int4 NULL,
	seq_num float4 NULL,
	amount float4 NULL,
	measure_unit_id int4 NULL,
	portion_description text NULL,
	modifier text NULL,
	gram_weight float4 NULL,
	data_points float4 NULL,
	footnote float4 NULL,
	min_year_acquired float4 NULL
);

CREATE TABLE public.ingredient_nutrient (
	id int4 NULL,
	fdc_id int4 NULL,
	nutrient_id int4 NULL,
	amount float4 NULL,
	data_points float4 NULL,
	derivation_id float4 NULL,
	min float4 NULL,
	max float4 NULL,
	median float4 NULL,
	footnote text NULL,
	min_year_acquired float4 NULL
);

CREATE TABLE public.ingredients (
	fdc_id int4 NOT NULL,
	data_type text NULL,
	description text NULL,
	food_category_id float4 NULL,
	publication_date text NULL,
	CONSTRAINT ingredients_pkey PRIMARY KEY (fdc_id)
);

CREATE TABLE public.meal (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	mealtime text NULL,
	"date" text NULL,
	CONSTRAINT meal_pkey PRIMARY KEY (id)
);

CREATE TABLE public.recipe (
	id serial4 NOT NULL,
	"name" text NULL,
	steps text NULL,
	CONSTRAINT recipe_pkey PRIMARY KEY (id)
);

CREATE TABLE public.meal_recipes (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	meal_id int4 NOT NULL,
	recipe_id int4 NULL,
	CONSTRAINT meal_recipes_pkey PRIMARY KEY (id),
	CONSTRAINT meal_recipes_meal_id_fkey FOREIGN KEY (meal_id) REFERENCES public.meal(id),
	CONSTRAINT meal_recipes_recipe_id_fkey FOREIGN KEY (recipe_id) REFERENCES public.recipe(id)
);

CREATE TABLE public.measure_unit (
	id int4 NULL,
	"name" text NULL
);

CREATE TABLE public.nutrient (
	id int4 NULL,
	"name" text NULL,
	unit_name text NULL,
	nutrient_nbr float4 NULL,
	"rank" float4 NULL
);

CREATE TABLE public.recipe_amounts (
	recipe_id int4 NULL,
	amount int4 NULL,
	ingredient_id int4 NULL
);

CREATE TABLE public.user_ingredients (
	fdc_id int4 NULL,
	amount int4 NULL,
	description text NULL,
	measure_unit_name text NULL
);


INSERT INTO ingredients (fdc_id, data_type, description, food_category_id, publication_date) VALUES
(748967, 'foundation_food', 'EGGS, GRADE A, LARGE, egg whole', 1, '2019-12-16');

INSERT INTO measure_unit (id, name) VALUES
(1099, 'egg')

INSERT INTO public.food_portion (id, fdc_id, seq_num, amount, measure_unit_id, portion_description, modifier, gram_weight, data_points, footnote, min_year_acquired)
VALUES (1099, 748967, 1, 1, 1099, NULL, 'whole without shell', 50.3, 526, NULL, 2019);


INSERT INTO ingredient_nutrient (fdc_id, nutrient_id, amount) VALUES
(748967, 1008, 148),
(748967, 1003, 12.4),
(748967, 1004, 9.96);
